### PR TITLE
Said0805

### PR DESCRIPTION
**Pull request by awhoa**
Navigation bar, profile page (should be replaced by the page Timon created), edit page created (navbar icons miss links to post list and comment list page).

### CODE REVIEW

**Comment by melihcatal** [comment]
@awhoa Hi! What's the plan for the conflicts ?

**Comment by awhoa** [comment]
I will look at them on the weekend.

Cheers

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Review by carolernst-uzh — APPROVED** [review]
I've gone through all the changes in this pull request and they look really good, no issues. I've merged the pull request accordingly.

**Comment by melihcatal** [comment]
Thanks for your review Carol! And thanks for your work Said! Currently you merged the master branch into the said's branch. If you are all okay with the pr, please merge said's branch into the master branch and close the pr :)

**Comment by carolernst-uzh** [comment]
@melihcatal I think it should be merged correctly now:
image

**Comment by melihcatal** [comment]
Yep, all perfect ! Thanks a lot :)

**Pull request merged**
